import React, { useState, useEffect } from 'react';
import { AlertOctagon, RotateCcw, ChevronDown, ChevronUp, FileCode, CheckCircle } from 'lucide-react';

export default function ErrorPanel({ error, onRetry, onManualLoad, onReset }) {
  const [showRawOutput, setShowRawOutput] = useState(false);
  const [editedJson, setEditedJson] = useState('');
  const [manualFixError, setManualFixError] = useState(null);

  // Sync editedJson with error.rawOutput on mount or change
  useEffect(() => {
    if (error?.rawOutput) {
      setEditedJson(
        typeof error.rawOutput === 'string' 
          ? error.rawOutput 
          : JSON.stringify(error.rawOutput, null, 2)
      );
    } else {
      setEditedJson('');
    }
    setManualFixError(null);
  }, [error]);

  const handleApplyFix = () => {
    setManualFixError(null);
    const result = onManualLoad(editedJson);
    if (!result.success) {
      setManualFixError({
        message: result.error,
        validationErrors: result.validationErrors
      });
    }
  };

  const getErrorTypeLabel = (type) => {
    switch (type) {
      case 'NETWORK_ERROR': return 'Network Connectivity Error';
      case 'API_ERROR': return 'Generative Model API Exception';
      case 'JSON_PARSE_ERROR': return 'Response Parser Syntax Error';
      case 'SCHEMA_VALIDATION_ERROR': return 'Itinerary Structure Schema Mismatch';
      case 'USER_CANCELED': return 'Generation Canceled';
      default: return 'Unexpected System Error';
    }
  };

  return (
    <div className="error-panel glass-panel">
      <div className="error-header">
        <div className="error-icon-box">
          <AlertOctagon size={28} />
        </div>
        <div className="error-title-group">
          <h2>{getErrorTypeLabel(error?.type)}</h2>
          <p>{error?.message || 'An unknown error occurred during itinerary compilation.'}</p>
        </div>
      </div>

      {/* Schema errors breakdown list */}
      {error?.validationErrors && error.validationErrors.length > 0 && (
        <div className="error-details">
          <h4 style={{ fontSize: '0.85rem', marginBottom: '8px', color: 'var(--text-primary)' }}>Validation Errors:</h4>
          <ul className="error-list">
            {error.validationErrors.map((err, i) => (
              <li key={i} className="error-list-item">
                <span style={{ color: 'var(--danger)' }}>•</span>
                <span>{err}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Actions */}
      <div className="error-actions">
        {onRetry && error?.type !== 'USER_CANCELED' && (
          <button className="glow-btn" onClick={onRetry}>
            <RotateCcw size={16} />
            Try Regenerating Itinerary
          </button>
        )}
        
        <button className="outline-btn" onClick={onReset}>
          Return to Input Form
        </button>
      </div>

      {/* Raw output editor accordion */}
      {error?.rawOutput && (
        <div className="raw-output-accordion">
          <div 
            className="accordion-toggle" 
            onClick={() => setShowRawOutput(!showRawOutput)}
          >
            <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
              <FileCode size={16} />
              {showRawOutput ? 'Hide raw output inspector & editor' : 'Inspect raw model output & apply manual fix'}
            </span>
            {showRawOutput ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
          </div>

          {showRawOutput && (
            <div className="raw-json-editor-wrapper">
              <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                You can review the raw response text generated by the model below. 
                If the model output was truncated or slightly malformed, you can fix the JSON syntax directly in the editor below and apply it.
              </p>
              
              <textarea
                className="raw-json-textarea"
                value={editedJson}
                onChange={(e) => setEditedJson(e.target.value)}
                placeholder="Paste or edit JSON here..."
              />

              {manualFixError && (
                <div className="error-details" style={{ borderColor: 'var(--danger)', marginTop: '8px' }}>
                  <p style={{ color: 'var(--danger)', fontWeight: 600, fontSize: '0.85rem' }}>
                    Repair Attempt Failed: {manualFixError.message}
                  </p>
                  {manualFixError.validationErrors && (
                    <ul className="error-list" style={{ marginTop: '4px' }}>
                      {manualFixError.validationErrors.map((err, i) => (
                        <li key={i} style={{ fontSize: '0.75rem' }}>• {err}</li>
                      ))}
                    </ul>
                  )}
                </div>
              )}

              <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '8px' }}>
                <button 
                  type="button" 
                  className="glow-btn" 
                  style={{ backgroundColor: 'var(--success)' }}
                  onClick={handleApplyFix}
                >
                  <CheckCircle size={16} />
                  Validate & Load JSON
                </button>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
