/**
 * Repairs malformed or truncated JSON strings generated by LLMs.
 * It handles:
 * 1. Stray trailing commas before closing braces/brackets.
 * 2. Unescaped internal quotes (best effort).
 * 3. Truncated JSON (closes unclosed strings, objects, and arrays).
 */
export function repairJson(jsonString) {
  if (!jsonString) return '';
  
  let repaired = jsonString.trim();

  // 1. Remove markdown code block wrappers if present (e.g. ```json ... ```)
  if (repaired.startsWith('```')) {
    const lines = repaired.split('\n');
    if (lines[0].startsWith('```json') || lines[0].startsWith('```')) {
      lines.shift();
    }
    if (lines[lines.length - 1].startsWith('```')) {
      lines.pop();
    }
    repaired = lines.join('\n').trim();
  }

  // 2. Remove trailing commas before closing brackets/braces
  repaired = repaired.replace(/,\s*([\]}])/g, '$1');

  // 3. Balance unclosed quotes, brackets, and braces (truncation repair)
  let inString = false;
  let escapeNext = false;
  const stack = [];

  for (let i = 0; i < repaired.length; i++) {
    const char = repaired[i];

    if (escapeNext) {
      escapeNext = false;
      continue;
    }

    if (char === '\\') {
      escapeNext = true;
      continue;
    }

    if (char === '"') {
      inString = !inString;
      continue;
    }

    // Only track brackets/braces outside of strings
    if (!inString) {
      if (char === '{' || char === '[') {
        stack.push(char);
      } else if (char === '}') {
        if (stack.length > 0 && stack[stack.length - 1] === '{') {
          stack.pop();
        }
      } else if (char === ']') {
        if (stack.length > 0 && stack[stack.length - 1] === '[') {
          stack.pop();
        }
      }
    }
  }

  // If we ended inside a string, close it
  if (inString) {
    repaired += '"';
  }

  // Close open brackets/braces in reverse order
  while (stack.length > 0) {
    const openChar = stack.pop();
    if (openChar === '{') {
      repaired += '}';
    } else if (openChar === '[') {
      repaired += ']';
    }
  }

  return repaired;
}

/**
 * Attempts to parse a JSON string, applying repairs if standard parsing fails.
 * Throws a descriptive error if parsing is still impossible.
 */
export function safeJsonParse(jsonString) {
  try {
    // Attempt standard parse first
    return {
      data: JSON.parse(jsonString),
      repaired: false
    };
  } catch (initialError) {
    console.warn("Initial JSON parse failed, attempting repair...", initialError);
    
    const repairedString = repairJson(jsonString);
    try {
      return {
        data: JSON.parse(repairedString),
        repaired: true,
        repairedString
      };
    } catch (repairError) {
      console.error("JSON repair failed as well:", repairError);
      throw new Error(`Invalid JSON syntax. Standard parse failed: "${initialError.message}". Repair attempt also failed: "${repairError.message}".`);
    }
  }
}
